name: vis-network CI

on:
  push:
    branches:
      - main
    paths:
      - workspaces/vis-network/**
  pull_request:
    paths:
      - workspaces/vis-network/**

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]
      fail-fast: false
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install --ignore-scripts
      - name: Build
        run: npm run build
      - name: Run tests
        run: npm run test -w workspaces/vis-network
